apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
  labels:
    app: canary
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: canary
        pipecd.dev/variant: primary
    spec:
      containers:
      - name: helloworld
        image: ecr.ap-northeast-1.amazonaws.com/lambda-test:v0.0.1
        args:
          - server
        ports:
        - containerPort: 9085