apiVersion: pipecd.dev/v1beta1
kind: EventWatcher
spec:
  events:
    # For those who want to identify Events using labels.
    - name: image-update
      replacements:
        - file: kubernetes/canary/deployment.yaml
          yamlField: $.spec.template.spec.containers[0].image
